# Available translations: en, ru
# If you want to translate yourself, create a file "{lang_code}.yml" and specify {lang_code} below
locale: "en"

# Setup instructions here: https://wiki.shandy.dev/en/AutoMessages/introduction
messages:
  message1:
    prefix: "[Сервер] "
    prefix-color: green
    message-lines:
      - line1:
          text: "Привет!"
          color: red
          style: bold
      - line2:
          text: "Это автоматическое сообщение."
          color: yellow
          style: italic
      - line3:
          text: "Ссылка на Discord"
          color: blue
          style: underlined
          link: "https://shandy.dev/discord"
    interval: 60
