name: AutoMessages
version: '${version}'
main: dev.shandy.automessages.AutoMessages
api-version: '1.20'
load: STARTUP
commands:
  am:
    description: "Automessages command"
    usage: "/am"
    aliases: [ "automsg", "automessages" ]
    permission: permission.op
    permission-message: "У Вас нет прав на использование этой комманды"
permissions:
  permission.op:
    description: "OP"
    default: op
